#! /usr/bin/env bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
#
# For documentation and help see:
#    https://github.com/mulle-nat/mulle-project
#
# Run this somewhat like this (for real: remove -n):
#    mulle-project-release -v -n --publisher mulle-nat --publisher-tap mulle-kybernetik/software/
#

if [ "${TRACE}" = "YES" ]
then
    set -x
fi

main()
{
   if [ ! -d "mulle-project" ]
   then
      echo "No mulle-project folder found." >&2
      exit 1
   fi

   if [ -z "`command -v "mulle-project-env"`" ]
   then
      cat <<EOF >&2
mulle-project-env not found in PATH.
Visit the homepage for installation instructions:
   https://github.com/mulle-nat/mulle-project
EOF
      exit 1
   fi

   INSTALLED_MULLE_PROJECT_VERSION="`"mulle-project-env" version`" || exit 1
   LIBEXEC_DIR="`mulle-project-env libexec-path`" || exit 1

   . "${LIBEXEC_DIR}/mulle-files.sh"       || exit 1
   . "${LIBEXEC_DIR}/mulle-publisher.sh"   || exit 1
   . "${LIBEXEC_DIR}/mulle-homebrew.sh"    || exit 1
   . "${LIBEXEC_DIR}/mulle-git.sh"         || exit 1
   . "${LIBEXEC_DIR}/mulle-version.sh"     || exit 1
   . "${LIBEXEC_DIR}/mulle-environment.sh" || exit 1

   #
   # dial past options now as they have been parsed
   #
   if [ "${DO_GIT_RELEASE}" != "YES" -a "${DO_GENERATE_FORMULA}" != "YES" ]
   then
      fail "Nothing to do! mulle-project/version-info.sh and mulle-project/formula-info.sh are missing"
   fi

   if [ "${DO_GIT_RELEASE}" = "YES" ]
   then
     # do the release
      git_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" || exit 1
   fi

   if [ "${DO_GENERATE_FORMULA}" = "YES" ]
   then
      if [ -z "${PUBLISHER}" ]
      then
         fail "You need to specify a publisher with --publisher (hint: https://github.com/<publisher>)"
      fi

      if [ -z "${PUBLISHER_TAP}" ]
      then
         fail "You need to specify a publisher tap with --tap (hint: <mulle-kybernetik/software>)"
      fi

      # generate the formula and push it
      if ! homebrew_main "${PROJECT}" \
                         "${NAME}" \
                         "${VERSION}" \
                         "${DEPENDENCIES}" \
                         "${BUILD_DEPENDENCIES}" \
                         "${HOMEPAGE_URL}" \
                         "${DESC}" \
                         "${ARCHIVE_URL}" \
                         "${HOMEBREW_TAP}" \
                         "${RBFILE}"
      then
         return 1
      fi
   fi

   #
   # check if someone installed a post_release function
   # if yes call it (maybe calls mulle-project-debian)
   #
   if [ "`type -t post_release`" = "function" ]
   then
      post_release "${PROJECT}" \
                   "${NAME}" \
                   "${VERSION}" \
                   "${DEPENDENCIES}" \
                   "${BUILD_DEPENDENCIES}" \
                   "${HOMEPAGE_URL}" \
                   "${DESC}" \
                   "${ARCHIVE_URL}" \
                   "${DEBIAN_DEPENDENCIES}"
   fi
}


MULLE_BOOTSTRAP_FAIL_PREFIX="`basename -- $0`"

main "$@"
