#! /bin/sh

#
# we have a different name for this command, because the chance of
# forgetting a parameter is high and accidentally running a proper
# mulle-project-distribute is hard to roll back
#

mulle-project-distribute \
   "$@" \
   --branch prerelease  \
   --latest-tag latest-prerelease \
   --no-version-tag \
   --no-formula \
   --no-push-formula \
   --no-post-release
