#! /usr/bin/env mulle-bash
# shellcheck shell=bash

[ "${TRACE}" = 'YES' -o "${MULLE_REPLACE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="0.0.0"



print_flags()
{
   echo "   -f          : force operation on protected files"
   echo "   -1          : replace only once per line"
   echo "   --regex     : use sed regexp"
   echo "   --          : skip options"

   ##
   ## ADD YOUR FLAG DESCRIPTION HERE
   ##

   options_technical_flags_usage "       : "
}


usage()
{
   [ $# -ne 0 ] && log_error "$*"


   cat <<EOF >&2
Usage:
   mulle-replace [flags] <find> <replace> <file>

   Replace a string with another string in a file.

   You will need to escape the '/' characters, if you choose the --regex
   option.
   
Flags:
EOF
   print_flags | LC_ALL=C sort >&2

   exit 1
}



delete_line()
{
   log_entry delete_line "$@"

   local find="$1"
   local filename="$2"

   local escaped_find

   if [ "${OPTION_ESCAPE}" = 'YES' ]
   then
      r_escaped_sed_pattern "${find}"
      escaped_find="${RVAL}"
   else
      escaped_find="${find}"
   fi

   local before
   local after

   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      before="`rexekutor cat "${filename}"`"
   fi

   if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' -a "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      after="`rexekutor sed "/${escaped_find}/d" "${filename}" `" || return 1
      log_verbose "Changes"
      rexekutor diff -b <( echo "${before}") <( echo "${after}" ) >&2
      return $?
   fi

   local unprotect

   if [ "${MULLE_FLAG_MAGNUM_FORCE}" = 'YES' -a ! -w "${filename}" ]
   then
      unprotect='YES'
   fi

   local permissions

   if [ "${unprotect}" = 'YES' ]
   then
      permissions="`lso "${filename}"`"
      exekutor chmod +w "${filename}"
   fi

   inplace_sed "/${escaped_find}/d" "${filename}" || return 1

   if [ "${unprotect}" = 'YES' ]
   then
      exekutor chmod "${permissions}" "${filename}"
   fi

   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      log_verbose "Changes"
      rexekutor diff -b <( echo "${before}") "${filename}" >&2
   fi
}


replace()
{
   log_entry replace "$@"

   local find="$1"
   local replace="$2"
   local filename="$3"

   local escaped_find
   local escaped_replace

   if [ "${OPTION_ESCAPE}" = 'YES' ]
   then
      r_escaped_sed_pattern "${find}"
      escaped_find="${RVAL}"

      r_escaped_sed_replacement "${replace}"
      escaped_replace="${RVAL}"
   else
      escaped_find="${find}"
      escaped_replace="${replace}"
   fi

   local DIFF

   if ! DIFF="`command -v diff`"
   then
      fail "diff command not installed"
   fi

   local before
   local after

   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      before="`rexekutor cat "${filename}"`"
   fi

   if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' -a "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      after="`rexekutor sed "s/${escaped_find}/${escaped_replace}/${OPTION_SED}" "${filename}" `" || return 1
      log_verbose "Changes"
      rexekutor "${DIFF}" -b <( echo "${before}") <( echo "${after}" ) >&2
      return 0
   fi

   local unprotect

   if [ "${MULLE_FLAG_MAGNUM_FORCE}" = 'YES' -a ! -w "${filename}" ]
   then
      unprotect='YES'
   fi

   local permissions

   if [ "${unprotect}" = 'YES' ]
   then
      permissions="`lso "${filename}"`"
      exekutor chmod +w "${filename}"
   fi

   inplace_sed "s/${escaped_find}/${escaped_replace}/${OPTION_SED}" "${filename}" || return 1

   if [ "${unprotect}" = 'YES' ]
   then
      exekutor chmod "${permissions}" "${filename}"
   fi

   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      log_verbose "Changes"
      rexekutor "${DIFF}" -b <( echo "${before}") "${filename}" >&2
   fi

   return 0
}


main()
{
   local MULLE_FLAG_MAGNUM_FORCE='NO'

   # technical flags
   local MULLE_TRACE
   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
   local MULLE_FLAG_LOG_LOCAL='NO'
   local MULLE_FLAG_LOG_DEBUG='NO'
   local MULLE_FLAG_LOG_EXEKUTOR='NO'
   local MULLE_FLAG_LOG_FLUFF='NO'
   local MULLE_FLAG_LOG_SCRIPTS='NO'
   local MULLE_FLAG_LOG_SETTINGS='NO'
   local MULLE_FLAG_LOG_VERBOSE='NO'
   local MULLE_FLAG_LOG_MERGE='NO'
   local MULLE_TRACE_POSTPONE='NO'

   local OPTION_SED="g"
   local OPTION_ESCAPE='YES'
   local OPTION_DELETE_LINE='NO'

   #
   # simple flag handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE='YES'
         ;;

         -h*|--help|help)
            usage
         ;;

         -1|--once)
            OPTION_SED=""
         ;;

         --delete-line)
            OPTION_DELETE_LINE="YES"
         ;;

         -g|--global)
            OPTION_SED="g"
         ;;

         --regex|--regexp)
            OPTION_ESCAPE='NO'
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         --)
            shift
            break
         ;;

         ##
         ## ADD YOUR FLAGS HERE
         ##

         -*)
            usage "Unknown flag \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   local rval

   if [ "${OPTION_DELETE_LINE}" = 'YES' ]
   then
      [ $# -lt 2 ] && usage "missing argument"

      local find="$1"

      shift 1

      while [ $# -ne 0 ]
      do
         delete_line "${find}" "$1" || return $?
         shift
      done
      return $?
   fi

   [ $# -lt 3 ] && usage "missing argument"

   local find="$1"
   local replace="$2"

   shift 2

   while [ $# -ne 0 ]
   do
      replace "${find}" "${replace}" "$1" || return $?
      shift
   done
   return $?
}


call_with_flags "main" "${MULLE_REPLACE_FLAGS}" "$@"
