#! /bin/sh

[ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_SQUASH_PRERELEASE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"

MULLE_EXECUTABLE_VERSION="0.0.0"

##########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################
# #
# # PRELUDE - Standard startup code for loading mulle-bashfunctions
# #
###

#
# Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
#
if ! [ ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR+x} ]
then
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
   export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
fi

#
# The booter reruns the executable either with bash or zsh, whatever the
# system provides. On the second run --no-auto-shell will be set first.
#
if [ "${1:-}" != --no-auto-shell ]
then
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
else
   shift    # get rid of --no-auto-shell
fi


#
# Include mulle-bashfunctions.sh         : default functions
#         mulle-bashfunctions-none.sh    : almost no functions
#         mulle-bashfunctions-minimal.sh : few functions for basic scripts
#         mulle-bashfunctions-all.sh     : everything, even obscure functions
#
# Do this first to get aliases
#
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

###
# # Now we are in bash or zsh with mulle-bashfunctions loaded
# #
###########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################

MULLE_EXECUTABLE="${BASH_SOURCE[0]:-${(%):-%x}}"

if [ -z "${MULLE_PROJECT_LIBEXEC_DIR}" ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-project" "mulle-project-git.sh"
   MULLE_PROJECT_LIBEXEC_DIR="${RVAL}"
fi



print_flags()
{
   echo "   -f     : force operation"
   echo "   -mulle : pass thru to mulle-project-git-prerelease"

   ##
   ## ADD YOUR FLAGS DESCRIPTIONS HERE
   ##

   options_technical_flags_usage \
                "  : "
}


usage()
{
   [ $# -ne 0 ] && log_error "$*"


   cat <<EOF >&2
Usage:
   mulle-project-squash-prerelease [flags]

   Squash all leading commits that contain the word "prerelease" in the
   commit message into one commit. Flags are passed to 
   mulle-project-git-prerelease. (Hint: use --mulle)

Flags:
EOF
   print_flags | LC_ALL=C sort >&2

   exit 1
}



main()
{
   local MULLE_FLAG_MAGNUM_FORCE='NO'

   # technical flags
   local MULLE_TRACE
   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
   local MULLE_FLAG_LOG_LOCAL='NO'
   local MULLE_FLAG_LOG_DEBUG='NO'
   local MULLE_FLAG_LOG_EXEKUTOR='NO'
   local MULLE_FLAG_LOG_FLUFF='NO'
   local MULLE_FLAG_LOG_SCRIPTS='NO'
   local MULLE_FLAG_LOG_SETTINGS='NO'
   local MULLE_FLAG_LOG_VERBOSE='NO'
   local MULLE_FLAG_LOG_MERGE='NO'
   local MULLE_TRACE_POSTPONE='NO'

   local OPTION_WORD="prerelease"
   local OPTION_REV="HEAD"
   local OPTION_MULLE="HEAD"

   #
   # simple flag handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE='YES'
         ;;

         -h*|--help|help)
            usage
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         --mulle)
            OPTION_MULLE="$1"
         ;;

         --)
            shift 
            break
         ;;

         -*)
            usage "Unknown flag \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   include "project::git"

   if ! project::git::is_clean
   then
      fail "Project ${PWD#${MULLE_USER_PWD}/} is not pristine"
   fi

   exekutor git checkout "${GIT_DEFAULT_BRANCH:-master}" || return 1

   local commit
   local count
   local message

   count=0
   for commit in `rexekutor git rev-list "${OPTION_REV}" `
   do     
      message="`git log -1 --pretty='format:%s' "${commit}" `"
      if ! grep -q -s -w "${OPTION_WORD}" <<< "${message}"
      then 
         break        
      fi
      count=$((count + 1))
   done

   case "${count}" in 
      0|1)
         log_info "Nothing to squash"
         return 0
      ;;
   esac

   log_info "Squashing ${count} contiguous prerelease commits"

   exekutor git reset --soft HEAD~${count} && 
   exekutor git commit -m "${OPTION_WORD}" || return 1

   log_info "Pushing prerelease changes"

   exekutor mulle-project-git-prerelease -f --clobber ${OPTION_MULLE} "$@"
}


call_with_flags "main" "${MULLE_PROJECT_SQUASH_PRERELEASE_FLAGS}" "$@"
