#! /usr/bin/env mulle-bash
# shellcheck shell=bash

[ "${TRACE}" = 'YES' -o "${SHELL_ALL_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="0.0.0"


if [ -z "${MULLE_PROJECT_LIBEXEC_DIR}" ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-project" "mulle-project-git.sh"
   MULLE_PROJECT_LIBEXEC_DIR="${RVAL}"
fi


print_flags()
{

   ##
   cat <<EOF
   --all               : execute in all projects,subprojects,tests
   --directory <dir>   : enter subdirectory, before executing project command
   --eval              : evaluate command line, requires tricky quoting though
   --if <expr>         : ignore project if shell expression evaluates to false
   --ignore <name>     : ignore a project from REPOS, multiples are possible
   --others            : also execute in other projects, like demo
   --sde               : only execute in mulle-sde projects
   --output-no-header  : don't visually separate command output
   --parallel          : execute operations in parallel
   --repos-file <f>    : REPOS file to use
   --strict            : errors preempt
   --tests             : also execute in test directories
EOF
   if [ ! -z "${MULLE_TRACE}" ]
   then
      cat <<EOF
   --if-exists <file>  : ignore project if <file> does not exist
   --lenient           : lenient operation, errors don't preempt (default)
   --main-project      : also execute in main project
   --sublime <file>    : create a "Sublime Text" project from REPOS
   --subprojects       : also execute in subprojects
   --only-others       : only execute in other projects, like demo
   --only-main-project : only execute in main project (default)
   --only-tests        : only execute in tests directories
   --only-subprojects  : only execute in subprojects project
   --skip-from <s>     : skip projects in REPOS starting with <s>
   --skip-until <s>    : skip projects in REPOS until <s>
   --skip-past <s>     : skip projects in REPOS until and including <s>
EOF
   fi

   ## ADD YOUR FLAG DESCRIPTION HERE
   ##

   options_technical_flags_usage \
                "               : "
}


usage()
{
   [ $# -ne 0 ] && log_error "$*"


   cat <<EOF >&2
Usage:
   mulle-project-all [flags] ...

   Execute a command in all projects that are defined by the file "REPOS"
   in the current directory. If there is no "REPOS" file, mulle-project-all
   will look for mulle-sde projects that reside in the current working
   directory (excluding the working directory itself) . Specialities like
   --tests, --subprojects, --others will only work with mulle-sde projects.
   With a REPOS file, mulle-project-all will work with non-mulle-sde projects
   as well.

   mulle-project-all can execute commands in parallel on all repositories with
   the --parallel option.

   mulle-project-all in --eval mode, will define a couple of environment
   variables for evaluation use:

      NAME            : basename of the directory
      PROJECT_NAME    : name of the main project

      SUBPROJECT_NAME : set if its a subproject
      OTHER_NAME      : set if its an other project test
      TEST_NAME       : set if its a test

   These values are alsot available in the --if expression.

Examples:
   List git status of all projects:
      mulle-project-all --parallel --output-no-header git status -s

   Create a .gitattributes file for projects under git control:
      mulle-project-all --if "[ -d .git ]" cp /tmp/.gitattributes .

   Generate hacky include statements for all projects:
      mulle-project-all -s --eval printf '%s\\\\n' '\#include\ \<\${NAME}.h\>'

Flags:
EOF
   print_flags | LC_ALL=C sort >&2

   if [ -z "${MULLE_TRACE}" ]
   then
   cat <<EOF >&2
      (use -v flag to see more options)
EOF
   fi
   echo "" >&2

   cat <<EOF >&2
Tip:
   It's convenient and conventional to put an \`alias mpa=mulle-project-all\`
   into your .bash_profile.

EOF

   exit 1
}

#############          1         2         3         4         5         6         7
#############012345678901234567890123456789012345678901234567890123456789012345678901
long_dashes="------------------------------------------------------------------------"
long_spaces="                                                                        "

##############0123456789012345678901234
short_dashes="-------------------------"
short_spaces="                     "

dashes="${long_dashes}"
spaces="${long_spaces}"

log_title()
{
   local s="$1"
   local len

   if [ -z "${NO_COLOR:-}" -a "${MULLE_NO_COLOR:-}" != 'YES' ] && [ ! -f /dev/stderr ]
   then
      len=$(( ${#dashes} - ${#s} ))
      if [ ${len} -lt 0 ]
      then
         len=0
      fi

      case "${MULLE_UNAME}" in 
         darwin)      
            printf "%b%b%s%s%b\n" "\033[1;106m" "${C_BOLD}" "$s" "${spaces:0:${len}}" "${C_RESET}"
         ;;

         *)
            printf "%b%b%s%s%b\n" "\033[0;44m" "${C_BOLD}" "$s" "${spaces:0:${len}}" "${C_RESET}"
         ;;
      esac
   else
      printf "%s\n" "$s"
   fi
}


log_title_verbose()
{
   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
   then
      log_title "$@"
   fi
}


shell_it()
{
   log_entry "shell_it" "$@"

   [ -z "$1" ] && return

   (
      rexekutor cd "$1" || exit 1

      r_basename "$1"
      NAME="$RVAL"

      if [ ! -z "${OPTION_IF}" ]
      then
         if ! NAME="'${NAME}'" \
              PROJECT_NAME="'${PROJECT_NAME}'" \
              SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
              OTHER_NAME="'${OTHER_NAME}'" \
              TEST_NAME="'${TEST_NAME}'" \
              eval_exekutor "${OPTION_IF}"
         then
            log_info "Skip ${C_RESET_BOLD}$1"
            return
         fi
      fi

      case ",${OPTION_ADORN}," in
         *,no-bar,*|*,no-top-bar,*|*,none,*)
         ;;

         *)
            log_title_verbose "${dashes}"
         ;;
      esac

      case ",${OPTION_ADORN}," in
         *,no-echo,*|*,no-printf,*|*,none,*)
         ;;

         *,printf,*)
            printf "%s " "$1"
         ;;

         *)
            log_title "$1"
         ;;
      esac

      case ",${OPTION_ADORN}," in
         *,no-bar,*|*,no-bottom-bar,*|*,none,*)
         ;;

         *)
            log_title_verbose "${dashes}"
         ;;
      esac


      shift

      if [ ! -z "${OPTION_DIRECTORY}" ]
      then
         if [ ! -d "${OPTION_DIRECTORY}" ]
         then
            log_warning "Warning \"${OPTION_DIRECTORY}\" is missing (skipped)"
            exit 0
         fi
         cd "${OPTION_DIRECTORY}" || exit 1
      fi

      if [ "${OPTION_EVAL}" = 'YES' ]
      then
         eval_exekutor NAME="'${NAME}'" \
                       PROJECT_NAME="'${PROJECT_NAME}'" \
                       SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
                       OTHER_NAME="'${OTHER_NAME}'" \
                       TEST_NAME="'${TEST_NAME}'" \
                       "$@"
         return $?
      fi

      exekutor "$@"
   )
}


project_it()
{
   log_entry "project_it" "$1" "$2" ...

   local project="$1"
   local mode="$2"

   shift 2

   local old

   case ",${mode}," in
      *,main-project,*)
         if [ -z "${PROJECT_NAME}" ]
         then
            PROJECT_NAME="${project}"
         fi

         if [ "${OPTION_SDE_TEST}" = 'YES' ]
         then
            if [ ! -d "${project}/.mulle/share/sde" ]
            then
               log_info "No sde project in ${C_RESET_BOLD}${project}"
               return
            fi
         fi

         if ! shell_it "${project}" "$@" && [ "${OPTION_LENIENT}" = 'NO' ]
         then
            exit 1
         fi

         PROJECT_NAME=
      ;;
   esac

   case ",${mode}," in
      *,subprojects,*)
         local subprojects
         local subproject 

         subprojects="`( cd "${project}"  ; 
                         mulle-sde -N subproject list --force-format '%a\n' \
                                                      --output-no-header 2> /dev/null
                        ) `"

         old="${SUBPROJECT_NAME}"
         .foreachline subproject in ${subprojects}
         .do
            case "${subproject}" in
               craftinfo/*)
                  # ignore
               ;;

               *)
                  if [ -d "${project}/${subproject}" ]
                  then
                     SUBPROJECT_NAME="${subproject}" ; export SUBPROJECT_NAME

                     project_it "${project}/${subproject}" "${mode}" "$@"
                  fi
               ;;
            esac
         .done

         SUBPROJECT_NAME="${old}"
      ;;
   esac

   case ",${mode}," in
      *,tests,*)
         local tests 
         local test 

         tests="`( cd "${project}" ; mulle-env --search-here environment \
                                       get --lenient MULLE_SDE_TEST_PATH 2> /dev/null )`"
         tests="${tests:-test}"

         old="${TEST_NAME}"
         .foreachpath test in ${tests}
         .do
            if [ -d "${project}/${test}" ]
            then
               TEST_NAME="${test}"

               if ! shell_it "${project}/${test}" "$@" && [ "${OPTION_LENIENT}" = 'NO' ]
               then
                  exit 1
               fi
            fi
         .done

         TEST_NAME="${old}"
      ;;
   esac        

   case ",${mode}," in
      *,others,*)
         local others
         local other

         others="`( cd "${project}" ; mulle-env --search-here environment \
                           get MULLE_SDE_OTHER_PROJECTS_PATH 2> /dev/null )`"
         others="${others:-demo}"

         old="${OTHER_NAME}"
         .foreachpath other in ${others}
         .do
            if [ -d "${project}/${other}" ]
            then
               OTHER_NAME="${other}"

               project_it "${project}/${other}" "${mode}" "$@"
            fi
         .done

         OTHER_NAME="${old}"
      ;;
   esac
}


parallel_execute_argument_first()
{
   log_entry "parallel_execute_argument_first" "$@"

   local arguments="$1"
   local mode="$2"
   local exists_file="$3"

   shift 3

   local _parallel_statusfile
   local _parallel_maxjobs
   local _parallel_jobs
   local _parallel_fails

   [ $# -eq 0 ] && _internal_fail "missing commandline"

   __parallel_begin

   local argument

   .foreachline argument in ${arguments}
   .do
      if [ ! -z "${argument}" ]
      then
         if [ ! -z "${exists_file}" ] && [ ! -e "${argument}/${exists_file}" ]
         then
            .continue
         fi

         wait_for_available_job "${_parallel_maxjobs}"
         _parallel_jobs=$(($_parallel_jobs + 1))

         log_debug "Running job #${_parallel_jobs}: $*"

         (
            project_it "${argument}" "${mode}" "$@"
         ) &
      fi
   .done

   __parallel_end
}


r_repos_contents()
{
   log_entry "r_repos_contents" "$@"

   local reposfile="$1"
   local skipfrom="$2"
   local skipuntil="$3"
   local skippast="$4"

   local repos

   if [ -f "${reposfile}" ]
   then
      repos="`rexekutor grep -E -v '^#' "${reposfile}" | sed -e '/^[[:space:]]*$/d' `"
   else
      [ ! -z "${reposfile}" ] && fail "\"${reposfile}\" not found"

      shell_enable_nullglob
      repos="`ls -1d */.mulle/share/sde | sed -e "s/\/\.mulle\/share\/sde$//" `"
      shell_disable_nullglob
   fi

   if [ -z "${skipfrom}${skipuntil}${skippast}" ]
   then
      RVAL="${repos}"
      return
   fi

   if [ ! -z "${skipfrom}" ]
   then
      r_escaped_sed_pattern "${skipfrom}"
      skipfrom="/^${RVAL}\$/"
   fi

   local first

   if [ ! -z "${skipuntil}" ]
   then
      first="${skipuntil}"
      r_escaped_sed_pattern "${skipuntil}"
      skipuntil="/^${RVAL}\$/"
   fi

   if [ ! -z "${skippast}" ]
   then
      first=
      r_escaped_sed_pattern "${skippast}"
      skipuntil="/^${RVAL}\$/"  # sic
   fi

   r_add_line "${first}" "`rexekutor sed -e "${skipfrom:-0},${skipuntil:-"\$"}d" <<< "${repos}"`"
}


#
# hidden bonus code
print_header()
{
   cat <<EOF
{
   "folders":
   [
EOF

}

print_footer()
{
   cat <<EOF
   ],
}
EOF

}


print_ignore_stuff()
{
   cat <<EOF
         "binary_file_patterns":
         [
            "*.o",
            "*.lib",
            "*.log",
            "*.a",
            "*.so",
            "*.exe",
            "*.zip",
            "*.tgz",
            "*.bz2",
            "*.xz",
            "*.gif",
            "*.png",
            "*.jpg",
            "*.tiff"
         ],
         "file_exclude_patterns":
         [
            "*~",
            "*~.*",
            "*.chk",
            ".DS_Store",
            "._.DS_Store",
            "*.sublime-workspace",
            "tmp.*"
         ],
         "folder_exclude_patterns":
         [
            ".git",
            ".mulle/var",
            ".unison*",
            "addiction",
            "build",
            "Build",
            "kitchen",
            "dependency",
            "stash",
            "var"
         ],
EOF

}


create_sublime_text_meta_project()
{
   local repos="$1"

   print_header

   .foreachline i in ${repos}
   .do
      cat <<EOF
      {
         "path": "$i",
EOF
         print_ignore_stuff
         cat <<EOF

      },
EOF
   .done

   print_footer
 }



main()
{
   local OPTION_ADORN
   local OPTION_LENIENT='YES'
   local OPTION_MODE="main-project"
   local OPTION_REPOSFILE
   local OPTION_DIRECTORY
   local OPTION_PARALLEL
   local OPTION_SDE_TEST='NO'
   local OPTION_EVAL
   local OPTION_IF
   local OPTION_IGNORE
   local OPTION_SKIP_FROM
   local OPTION_SKIP_UNTIL
   local OPTION_PRINT
   local OPTION_SUBLIME

   #
   # simple flag handling
   #
   while [ $# -ne 0 ]
   do
      # this grabs -n -s -v
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage
         ;;

         -a|--all)
            OPTION_MODE="main-project,subprojects,tests,others"
         ;;

         -d|--directory)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift

            OPTION_DIRECTORY="$1"
         ;;

         -e|--eval)
            OPTION_EVAL='YES'
         ;;

         -i|--ignore)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift

            r_add_line "${OPTION_IGNORE}" "$1"
            OPTION_IGNORE="${RVAL}"
         ;;

         --if)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift

            r_concat "${OPTION_IF}" "$1" "&&"
            OPTION_IF="${RVAL}"
         ;;

         --if-exists|--if-file|--if-exists-file)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift

            r_concat "${OPTION_IF}" "[ -e \"$1\" ]"
            OPTION_IF="${RVAL}"
         ;;

         -l|--lenient)
            OPTION_LENIENT='YES'
         ;;

         -m|--main-project-only|--only-main-project)
            OPTION_MODE="main-project"
         ;;

         -p|--parallel)
            OPTION_PARALLEL='YES'
         ;;

         -o|--others-only|--only-others|--other-only|--only-other)
            OPTION_MODE="others"
         ;;

         -r|--repos-file)
            [ $# -eq 1 ] && usage "missing argument to $1"
            shift

            OPTION_REPOSFILE="$1"
         ;;

         -t|--tests-only|--only-tests|--test-only|--only-test)
            OPTION_MODE="tests"
         ;;

         --subprojects-only|--only-subprojects|--subproject-only|--only-subproject)
            OPTION_MODE="subprojects"
         ;;

         --others)
            r_comma_concat "${OPTION_MODE}" "others"
            OPTION_MODE="${RVAL}"
         ;;

         --short-dashes)
            dashes="${short_dashes}"
            spaces="${short_spaces}"
         ;;

         --main-project|--project)
            r_comma_concat "${OPTION_MODE}" "main-project"
            OPTION_MODE="${RVAL}"
         ;;

         --sde|--sde-test)
            OPTION_SDE_TEST='YES'
         ;;

         --skip-from)
            [ $# -eq 1 ] && usage "missing argument to $1"
            shift

            OPTION_SKIP_FROM="$1"
         ;;

         --skip-until)
            [ $# -eq 1 ] && usage "missing argument to $1"
            shift

            OPTION_SKIP_UNTIL="$1"
         ;;

         --skip-past)
            [ $# -eq 1 ] && usage "missing argument to $1"
            shift

            OPTION_SKIP_PAST="$1"
         ;;

         --print)
            OPTION_PRINT='YES'
         ;;

         --strict)
            OPTION_LENIENT='NO'
         ;;

         --sublime)
            [ $# -eq 1 ] && usage "missing argument to $1"
            shift

            OPTION_SUBLIME="$1"
         ;;

         --subprojects)
            r_comma_concat "${OPTION_MODE}" "subprojects"
            OPTION_MODE="${RVAL}"
         ;;

         --output-no-header)
            OPTION_ADORN="none"
         ;;

         --tests|--test)
            r_comma_concat "${OPTION_MODE}" "tests"
            OPTION_MODE="${RVAL}"
         ;;

         --version)
            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            usage "Unknown flag \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   if [ ! -z "${OPTION_SKIP_PAST}" -a ! -z "${OPTION_SKIP_UNTIL}" ]
   then
      fail "Specify --skip-until or --skip-past but not both"
   fi

   local repos

   r_repos_contents "${OPTION_REPOSFILE:-REPOS}" \
                    "${OPTION_SKIP_FROM}" \
                    "${OPTION_SKIP_UNTIL}" \
                    "${OPTION_SKIP_PAST}"
   repos="${RVAL}"

   if [ "${OPTION_PRINT}" = 'YES' ]
   then
      printf "%s\n" "${repos}"
      exit 0
   fi

   local text

   if [ ! -z "${OPTION_SUBLIME}" ]
   then
      if text="`create_sublime_text_meta_project "${repos}"`"
      then
         redirect_exekutor "${OPTION_SUBLIME}"  printf "%s\n" "${text}"
         exit 0
      fi
      exit 1
   fi

   if [ "${OPTION_PARALLEL}" = 'YES' ]
   then
      include "parallel"

      parallel_execute_argument_first "${repos}" \
                                      "${OPTION_MODE}" \
                                      "${OPTION_EXISTS_FILE}" \
                                      "$@"
      return $?
   fi

   local i

   .foreachline i in ${repos}
   .do
      if find_line "${OPTION_IGNORE}" "${i}"
      then
         .continue
      fi

      project_it "$i" "${OPTION_MODE}" "$@"
   .done
}


call_with_flags "main" "${MULLE_REPLACE_FLAGS}" "$@"
