#! /bin/sh
#
# MEMO: infer is pretty useless, it only caught boring stuff and false
#       positives. valgrinding is more useful
#
INFERFLAGS="--bufferoverrun --biabduction --pulse"

if [ "$1" == "--no-default" ]
then
   INFERFLAGS=
   shift
fi

if ! INFER="`command -v infer`"
then
   echo "Install https://github.com/facebook/infer" >&2
   exit 1
fi

mulle-sde clean && \
mulle-sde craft && \
infer run --compilation-database "`mulle-sde kitchen-dir`/Debug/compile_commands.json" ${INFERFLAGS} "$@"
