#! /usr/bin/env bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
#
# For documentation and help see:
#    https://github.com/mulle-sde/mulle-project
#
# Run this somewhat like this (for real: remove -n):
#    mulle-project-release -v -n --publisher mulle-nat --publisher-tap mulle-kybernetik/software/
#
[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


usage()
{
   cat <<EOF >&2
Usage: mulle-project-distribute [options]

   Distribute the project via github, homebrew, debian.

Options:
   --verify-only  : check but do not acually commit anything
EOF
   exit 1
}


source_file()
{
   log_verbose "Read \"$1\"" >&2
   . "$@"
}


project_is_compatible_version()
{
   local installed="$1"
   local script="$2"

   local s_major
   local s_minor
   local i_major
   local i_minor

   s_major="`echo "${script}"    | head -1 | cut -d. -f1`"
   s_minor="`echo "${script}"    | head -1 | cut -d. -f2`"
   i_major="`echo "${installed}" | head -1 | cut -d. -f1`"
   i_minor="`echo "${installed}" | head -1 | cut -d. -f2`"

   if [ "${i_major}" = "" -o "${i_minor}" = "" -o \
        "${s_major}" = "" -o "${s_minor}" = "" ]
   then
      return 2
   fi

   if [ "${i_major}" != "${s_major}" ]
   then
      return 1
   fi

   if [ "${i_minor}" -lt "${s_minor}" ]
   then
      return 1
   fi

   return 0
}



__environment_main()
{
   # --- COMMON ---

   if [ -z "${PROJECT}" ]
   then
      PROJECT="`basename -- "$PWD"`"
   fi

   #
   # NAME can usually be deduced, if you follow the conventions
   #
   if [ -z "${NAME}" ]
   then
      NAME="`get_formula_name_from_project "${PROJECT}" "${LANGUAGE}"`" || exit 1
   fi

   #
   # Use mulle-project-version to determine version
   #
   if [ -z "${VERSION}" ]
   then
      options="--no-info --no-tag-warning"
      [ ! -z "${LANGUAGE}" ]    && options="${options} --language \"${LANGUAGE}\""
      [ ! -z "${VERSIONNAME}" ] && options="${options} --versionname \"${VERSIONNAME}\""
      [ ! -z "${VERSIONFILE}" ] && options="${options} --versionfile \"${VERSIONFILE}\""

      VERSION="`eval mulle-project-version ${options} "${PROJECT}"`" || exit 1
   fi


   # --- FORMULA  ---


   # dependencies can be empty
   if [ -z "${DEPENDENCIES}" -a -f  .DEPENDENCIES ]
   then
      log_verbose "Read DEPENDENCIES from \".DEPENDENCIES\""
      DEPENDENCIES="`egrep -v '^#' .DEPENDENCIES`"
   fi

   MULLE_KYBERNETIK_TAP="${MULLE_KYBERNETIK_TAP:-mulle-kybernetik/software/}"
   case "${MULLE_KYBERNETIK_TAP}" in
      */)
      ;;

      *)
         MULLE_KYBERNETIK_TAP="${MULLE_KYBERNETIK_TAP}/"
      ;;
   esac

   MULLE_SDE_TAP="${MULLE_SDE_TAP:-mulle-kybernetik/software/}"
   case "${MULLE_SDE_TAP}" in
      */)
      ;;

      *)
         MULLE_SDE_TAP="${MULLE_SDE_TAP}/"
      ;;
   esac


   MULLE_NAT_TAP="${MULLE_NAT_TAP:-mulle-kybernetik/software/}"
   case "${MULLE_NAT_TAP}" in
      */)
      ;;

      *)
         MULLE_NAT_TAP="${MULLE_NAT_TAP}/"
      ;;
   esac

   MULLE_C_TAP="${MULLE_C_TAP:-mulle-kybernetik/software/}"
   case "${MULLE_C_TAP}" in
      */)
      ;;

      *)
         MULLE_C_TAP="${MULLE_C_TAP}/"
      ;;
   esac

   MULLE_OBJC_TAP="${MULLE_OBJC_TAP:-mulle-kybernetik/software/}"
   case "${MULLE_OBJC_TAP}" in
      */)
      ;;

      *)
         MULLE_OBJC_TAP="${MULLE_OBJC_TAP}/"
      ;;
   esac

   BUILDTOOLS_TAP="${BUILDTOOLS_TAP:-mulle-kybernetik/software/}"
   case "${BUILDTOOLS_TAP}" in
      */)
      ;;

      *)
         BUILDTOOLS_TAP="${BUILDTOOLS_TAP}/"
      ;;
   esac

   TOOLS_TAP="${TOOLS_TAP:-mulle-kybernetik/software/}"
   case "${TOOLS_TAP}" in
      */)
      ;;

      *)
         TOOLS_TAP="${TOOLS_TAP}/"
      ;;
   esac

   DEPENDENCY_TAP="${DEPENDENCY_TAP:-${PUBLISHER_TAP}}"
   case "${DEPENDENCY_TAP}" in
      */)
      ;;

      *)
         DEPENDENCY_TAP="${DEPENDENCY_TAP}/"
      ;;
   esac


   # where to grab the archive off
   ARCHIVE_URL="${ARCHIVE_URL:-https://github.com/${PUBLISHER}/${PROJECT}/archive/${VERSION}.tar.gz}"

   # written into formula for project, will be evaled
   HOMEPAGE_URL="${HOMEPAGE_URL:-https://github.com/${PUBLISHER}/${PROJECT}}"


   # --- HOMEBREW TAP ---

   #
   # Specify to where and under what name to publish via your brew tap
   #
   # require PUBLISHER (and PUBLISHER_TAP) as command line parameter, so
   # that forks don't have to edit this constantly
   #
   #
   TAPS_LOCATION="${TAPS_LOCATION:-..}"

   if [ ! -z "${PUBLISHER_TAP}" ]
   then
      tmp="`basename -- ${PUBLISHER_TAP}`"
      HOMEBREW_TAP="${HOMEBREW_TAP:-${TAPS_LOCATION}/homebrew-${tmp}}"
   fi

   RBFILE="${RBFILE:-${NAME}.rb}"


   # --- GIT ---

   if [ -z "${VERSION}" ]
   then
      fail "Could not figure out the version. (hint: use VERSIONNAME, VERSIONFILE)"
   fi

   # tag to tag your release
   TAG="${TAG:-${TAG_PREFIX}${VERSION}}"

   # git remote to push to, usually origin
   ORIGIN="${ORIGIN:-origin}"

   # git remote to push to, usually github, can be empty
   GITHUB="${GITHUB:-github}"

   # git branch to release to, source is always current
   BRANCH="${BRANCH:-release}"
}


main()
{
   DO_PUSH_FORMULA='YES'
   USE_CACHE='NO'
   OPTION_LATEST_TAG="latest"
   VERIFY_ONLY='NO'

   local DO_GIT_RELEASE="DEFAULT"
   local DO_GENERATE_FORMULA="DEFAULT"

   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage
         ;;

         # single arg long (kinda lame)
         --cache)
            USE_CACHE='YES'
         ;;

         --no-cache)
            USE_CACHE='NO'
         ;;

         --echo)
            OPTION_ECHO='YES'
         ;;

         --no-git)
            DO_GIT_RELEASE='NO'
         ;;

         --no-formula)
            DO_GENERATE_FORMULA='NO'
         ;;

         --no-latest-tag)
            OPTION_LATEST_TAG=""
         ;;

         --no-push)
            DO_PUSH_FORMULA='NO'
         ;;

         # arg long

         --buildtools-tap)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            BUILDTOOLS_TAP="$1"
         ;;

         --tools-tap)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            TOOLS_TAP="$1"
         ;;

         --branch)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            BRANCH="$1"
         ;;

         --dependency-tap)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            DEPENDENCY_TAP="$1"
         ;;

         --github)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            GITHUB="$1"
         ;;

         --homepage-url)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            HOMEPAGE_URL="$1"
         ;;

         --origin)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            ORIGIN="$1"
         ;;

         --project)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            PROJECT="$1"
         ;;

         --publisher)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            PUBLISHER="$1"
         ;;

         --publisher-tap)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            PUBLISHER_TAP="$1"
         ;;

         --tag)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            TAG="$1"
         ;;

         --tag-prefix)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            TAG_PREFIX="$1"
         ;;

         --taps-location)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
            shift
            TAPS_LOCATION="$1"
         ;;

         --verify-only)
            VERIFY_ONLY='YES'
         ;;

            # allow user to specify own parameters for his
            # generate_formula scripts w/o having to modify this file
         --*)
            [ $# -eq 1 ] && fail "missing parameter for \"$1\""

            varname="`sed 's/^..//' <<< "$1"`"
            varname="`tr '-' '_' <<< "${varname}"`"
            varname="`tr '[a-z]' '[A-Z]' <<< "${varname}"`"
            if ! egrep -q -s '^[A-Z_][A-Z0-9_]*$' <<< "${varname}" > /dev/null
            then
               fail "invalid variable specification \"${varname}\", created by \"$1\""
            fi

            shift
            eval "${varname}='$1'"
            log_info "User variable ${varname} set to \"$1\""
         ;;

         -*)
            log_error "Unknown option \"$1\""
            exit 1
         ;;
      esac

      shift
   done

   if [ ! -d ".mulle/etc/project" ]
   then
      log_warning "No .mulle/etc/project folder found."
   fi

   #
   # order of includes is important its a bit weird coded, due to being
   # old
   #
   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-user-files.sh" "$@"   || exit 1
   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-version.sh" "$@"      || exit 1
   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-publisher.sh" "$@"    || exit 1

  __environment_main

   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-homebrew.sh" "$@"       || exit 1
   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-git.sh" "$@"            || exit 1

   #
   # dial past options now as they have been parsed
   #
   if [ "${DO_GIT_RELEASE}" = "DEFAULT" -a -f VERSION -a ! -d mulle-project ]
   then
      # make most simplistic stuff work (nice for farmhash e.g.)
      DO_GIT_RELEASE='YES'
   fi

   if [ "${DO_GIT_RELEASE}" != 'YES' -a "${DO_GENERATE_FORMULA}" != 'YES' ]
   then
      fail "Nothing to do! .mulle/etc/project/version-info.sh and .mulle/etc/project/formula-info.sh are missing"
   fi

   if [ "${DO_GIT_RELEASE}" = 'YES' ]
   then
     # do the release
      git_verify_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || exit 1

      if [ "${VERIFY_ONLY}" != 'YES' ]
      then
         log_info "Git release..."

         git_commit_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || exit 1
      fi
   else
      log_fluff "No git release"
   fi

   if [ "${DO_GENERATE_FORMULA}" = 'YES' ]
   then
      if [ -z "${PUBLISHER}" ]
      then
         fail "You need to specify a publisher with --publisher (hint: https://github.com/<publisher>)"
      fi

      if [ -z "${PUBLISHER_TAP}" ]
      then
         fail "You need to specify a publisher tap with --tap (hint: <mulle-kybernetik/software>)"
      fi

      if [ "${VERIFY_ONLY}" != 'YES' ]
      then
         log_info "Homebrew formula..."

         # generate the formula and push it
         if ! homebrew_main "${PROJECT}" \
                            "${NAME}" \
                            "${VERSION}" \
                            "${DEPENDENCIES}" \
                            "${BUILD_DEPENDENCIES}" \
                            "${HOMEPAGE_URL}" \
                            "${DESC}" \
                            "${ARCHIVE_URL}" \
                            "${HOMEBREW_TAP}" \
                            "${RBFILE}"
         then
            log_error "Homebrew generation failed!"
            return 1
         fi
      fi
   else
      log_fluff "No homebrew formula"
   fi

   #
   # check if someone installed a post_release function
   # if yes call it (maybe calls mulle-project-debian)
   #
   if [ "${VERIFY_ONLY}" != 'YES' ]
   then
      if [ "`type -t post_release`" = "function" ]
      then
         log_info "Post release..."
         post_release "${PROJECT}" \
                      "${NAME}" \
                      "${VERSION}" \
                      "${DEPENDENCIES}" \
                      "${BUILD_DEPENDENCIES}" \
                      "${HOMEPAGE_URL}" \
                      "${DESC}" \
                      "${ARCHIVE_URL}" \
                      "${DEBIAN_DEPENDENCIES}"
      else
         log_fluff "No post release"
      fi
   fi
}


########
###
### INIT
###
_init()
{
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
         echo "mulle-bashfunctions are not installed" >&2 && \
      exit 1
   fi

   # shellcheck source=../mulle-bashfunctions/src/mulle-bashfunctions.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"

   MULLE_PROJECT_LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1

   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-git.sh" || exit 1
   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-version.sh" || exit 1

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   set -o pipefail
}


###
### INIT
###
########


_init "$@" # needs params
main "$@"
