#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_VERSION_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="0.0.0"


if [ -z "${MULLE_PROJECT_LIBEXEC_DIR}" ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-project" "mulle-project-git.sh"
   MULLE_PROJECT_LIBEXEC_DIR="${RVAL}"
fi


usage()
{
   [ "$#" -ne 0 ] && log_error "$1"

   cat <<EOF >&2
Usage: mulle-project-version <command> [options] [projectname]

   Manage project version information.

Commands:
   get                   : show current version (default)
   set <version>         : set version (use --write to persist)
   try <version>         : preview version change without writing
   init                  : create version-info.sh configuration
   add <file>            : add version mirror file
   remove <file>         : remove version mirror file
   list                  : show current configuration
   status                : check if version needs a bump
   diff                  : output version jump type (none, patch, minor, major)

Get/Set Options:
   ++                    : shorthand for --increment-patch --write
   --add-patch <value>   : add value to patch version part, needs --write
   --custom-versioning   : use custom versioning (four numbers)
   --first-patch-one     : set patch to 1 for minor/major increments
   --first-patch-zero    : set patch to 0 for minor/major increments
   --increment-major     : add 1 to major versionpart, needs --write
   --increment-minor     : add 1 to minor version part, needs --write
   --increment-patch     : add 1 to patch version part, needs --write
   --increment-custom    : add 1 to custom (fourth) version part, needs --write
   --if-needed           : increment, if needed only (determined by status)
   --language <name>     : project language, (c, obj, cpp, bash etc)
   --no-cmake            : do not edit CMakeLists.txt if it exists
   --no-info             : do not read -info.sh files
   --no-tag-warning      : do not warn if git tag exists
   --print-latest-tag    : print latest release tag
   --releasenotes        : read RELEASENOTES.md version
   --no-releasenotes     : ignore RELEASENOTES.md version
   --read-xcode-version  : read version from Xcode project
   --write               : update versionfile with new version
   --write-xcode-version : write version to Xcode project
   --xcodeproj <dir>     : specify path of .xcodeproj directory

Init Options:
   --file <path>         : version file path
   --name <varname>      : version variable name

Environment:
   VERSIONFILE           : File to look for master version number
   VERSIONNAME           : Variable name of the version number
   VERSIONCUSTOM         : Set to YES for custom versioning
   VERSIONFILEMIRRORS    : Other files containing the version number

EOF
   exit 1
}


get_xcodeproj_version()
{
   log_entry "get_xcodeproj_version" "$@"

   local filename="$1/project.pbxproj"

   if [ ! -f "${filename}" ]
   then
      fail "Xcode project file \"${filename}\" not found"
   fi

   grep -E '^[[:space:]]*CURRENT_PROJECT_VERSION[[:space:]]*=' "${filename}" | \
     head -1 | \
     sed 's|^[[:space:]]*CURRENT_PROJECT_VERSION[[:space:]]*=[[:space:]]*["]*\([0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*\).*|\1|'
}


get_version()
{
   log_entry "get_version" "$@"

   if [ "${OPTION_READ_XCODE_VERSION}" = 'YES' -o "${OPTION_WRITE_XCODE_VERSION}" = 'YES' ]
   then
      if [ -z "${ACTUAL_XCODEPROJ}" ]
      then
         log_verbose "Checking for existing Xcode project"

         ACTUAL_XCODEPROJ="`ls -1d *.xcodeproj | head -1`" 2> /dev/null
         if [ -z "${ACTUAL_XCODEPROJ}" ]
         then
            fail "No Xcode project found"
         fi
      fi

      XCODE_VERSION="`get_xcodeproj_version "${ACTUAL_XCODEPROJ}"`"
      if [ -z "${XCODE_VERSION}" ]
      then
         fail "could not read CURRENT_PROJECT_VERSION from \"${ACTUAL_XCODEPROJ}\""
      fi

      if [ "${OPTION_READ_XCODE_VERSION}" = 'YES' ]
      then
         VERSION="${XCODE_VERSION}"
      fi
   fi

   #
   # these can usually be deduced, if you follow the conventions
   #
   if [ -z "${VERSION}" ]
   then
      if [ -z "${LANGUAGE}" ]
      then
         LANGUAGE="`project::version::get_language_from_directoryname "${DIRECTORY_NAME}"`"
         log_verbose "LANGUAGE is \"${LANGUAGE}\""
      fi

      if [ -z "${VERSIONFILE}" ]
      then
         VERSIONFILE="`project::version::get_header_from_project "${PROJECT_NAME}" "${LANGUAGE}"`"
      fi

      # Don't auto-generate VERSIONNAME for CMakeLists.txt
      if [ -z "${VERSIONNAME}" -a "${VERSIONFILE}" != "CMakeLists.txt" ]
      then
         include "case"

         # hacky hack for mulle-objc
         case "${PROJECT_NAME}" in
            mulle-objc*)
               log_verbose "VERSIONNAME: Use special hack for mulle-objc- prefixed projects "
               r_smart_upcase_identifier "${PROJECT_NAME}"
               VERSIONNAME="${RVAL}_VERSION"
            ;;

            *)
               r_smart_file_upcase_identifier "${PROJECT_NAME}"
               VERSIONNAME="${RVAL}_VERSION"
            ;;
         esac
      fi

      if [ ! -f "${VERSIONFILE}" -a -f "VERSION" ]
      then
         VERSION="`grep -E -v '^#' "VERSION"`"
         if [ ! -z "${VERSION}" ]
         then
            VERSIONFILE="VERSION"
            VERSIONNAME=""
         fi
      else
         # Special handling for CMakeLists.txt with empty VERSIONNAME
         if [ "${VERSIONFILE}" = "CMakeLists.txt" -a -z "${VERSIONNAME}" ]
         then
            VERSION="`rexekutor grep -A10 "^project" "${VERSIONFILE}" \
                      | grep -E "project|VERSION"        \
                      | sed -n 's/.*VERSION[[:space:]]*"\([0-9]\+\.[0-9]\+\.[0-9]\+\)".*/\1/p' \
                      | head -n1`"
         else
            VERSION="`project::version::get_project_version "${VERSIONFILE}" "${VERSIONNAME}" "${VERSIONCUSTOM}"`"
         fi
         
         if [ -z "${VERSION}" ]
         then
            VERSION="`project::version::get_project_version "src/version.h" "${VERSIONNAME}" "${VERSIONCUSTOM}"`"
            if [ ! -z "${VERSION}" ]
            then
               VERSIONFILE="src/version.h"
            fi
         fi
      fi

      if [ -z "${VERSION}" -a -f "package.json" ]
      then
         VERSION="`grep -E '"version"[[:space:]]*:' "package.json" | sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)".*/\1/p' | head -1`"
         if [ ! -z "${VERSION}" ]
         then
            VERSIONFILE="package.json"
            VERSIONNAME="version"
         fi
      fi
   else
      VERSIONFILE=
   fi

   if [ -z "${VERSION}" ]
   then
      if [ "${OPTION_READ_CMAKELISTS_TXT}" = 'YES' -a -f 'CMakeLists.txt' ]
      then
         VERSION="`rexekutor grep -A10 "^project" CMakeLists.txt \
                   | grep -E "project|VERSION"        \
                   | sed -n 's/.*VERSION[[:space:]]*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p' \
                   | head -n1`"
         # we don't change VERSIONFILE here
      fi
   fi

   if [ -z "${VERSION}" ]
   then
      fail "Could not figure out the version for PROJECT_NAME=\"${PROJECT_NAME}\", \
LANGUAGE=\"${LANGUAGE}\", VERSIONNAME=\"${VERSIONNAME}\", \
VERSIONFILE=\"${VERSIONFILE}\".
Hint: specify VERSIONNAME, VERSIONFILE in .mulle/etc/project/version-info.sh"
   else
      log_fluff "Versionfile: ${VERSIONFILE}"
      log_fluff "Versionname: ${VERSIONNAME}"
   fi
}


get_latest_releasenote_version()
{
   log_entry "get_latest_releasenote_version" "$@"

   local filename="$1"

   if [ ! -f "${filename}" ]
   then
      log_debug "Releasenote file \"${filename}\" not found."
      return 1
   fi

   sed -n 's/^#*[[:space:]]*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/p' \
          "${filename}" \
   | head -1

   return 0
}


info_version()
{
   log_entry "info_version" "$@"

   local version="$1"
   local last="$2"

   if [ ! -z "${last}" ]
   then
      if [ "${version}" = "${last}" ]
      then
         # memo this doesn't happen as we warn before!
         log_info "Version is ${version}. Last git tag is same."
      else
         log_info "Version is ${C_MAGENTA}${C_BOLD}${version}${C_INFO}. Last git tag is ${C_RESET_BOLD}${last}${C_INFO}."
      fi
   else
      log_info "No git tag \"${version}\" exists. (git fetch --tags maybe ?)"
   fi
}


info_releasenotes()
{
   log_entry "info_releasenotes" "$@"

   local version="$1"

   local releasenotes_version

   if releasenotes_version="`get_latest_releasenote_version "RELEASENOTES.md"`"
   then
      if [ -z "${releasenotes_version}" ]
      then
         log_warning "No version found in RELEASENOTES.md"
      else
         if [ "${releasenotes_version}" != "${version}" ]
         then
            log_warning "Last RELEASENOTES.md version is ${releasenotes_version}"
         else
            log_info "Last RELEASENOTES.md version is ${version}"
         fi
      fi
   fi
}


status_version()
{
   log_entry "status_version" "$@"

   local info

   info=" "
   if project::git::can_amend
   then
      info=", amendable "
   fi

   local last

   last="`rexekutor git tag -l --sort=-creatordate 2> /dev/null | grep -E -x '[0-9]*\.[0-9]*\.[0-9]*' | head -1`"
   info_version "${VERSION}" "${last}"

   if [ "${OPTION_RELEASENOTES}" != 'NO' ]
   then
      info_releasenotes "${VERSION}"
   fi

   if [ -z "${last}" ]
   then
      log_info "Project has never been tagged, so version is probably OK."
      if ! project::git::is_clean
      then
         log_info "There are ${C_WARNING}uncommitted${info}${C_INFO}changes."
         return 1
      fi
      return 0
   fi

   if [ "${VERSION}" = "${last}" ]
   then
      local counts

      counts="`rexekutor git rev-list --left-right --count master...${last} `" || exit 1

      log_debug "Counts for master...${last}: ${counts}"

      # clumsy
      local master_count
      local last_count=0

      for count in ${counts}
      do
         if [ -z "${master_count}" ]
         then
            master_count="${count}"
         else
            last_count="${count}"
         fi
      done

      log_setting "master_count : ${master_count:-0}"
      log_setting "last_count   : ${last_count}"

      if [ ${master_count:-0} -gt 0 ]
      then
         log_warning "Project version needs a bump, as there are commits."
         if ! project::git::is_clean
         then
            log_info "There are ${C_WARNING}uncommitted${info}${C_INFO}changes."
            rexekutor mulle-project-commit -v -n --status ${MULLE_PROJECT_COMMIT_FLAGS}
         fi
         return 1
      fi

      if ! project::git::is_clean
      then
         log_warning "Project version needs a bump, as there are uncommitted${info}changes."
         rexekutor mulle-project-commit -v -n --status ${MULLE_PROJECT_COMMIT_FLAGS}
         return 1
      fi

      log_info "Project version is OK, as there are no changes."
      return 0
   fi

   if ! project::git::is_clean
   then
      log_info "Project version is already bumped, for the ${C_WARNING}uncommitted${info}${C_INFO}changes."
      rexekutor mulle-project-commit -v -n --status ${MULLE_PROJECT_COMMIT_FLAGS}
      return 1
   fi

   log_info "Project version is already bumped and there are no uncommitted changes."
   return 0
}



warn_version()
{
   log_entry "warn_version" "$@"

   local warn="$1"

   if project::git::tag_exists "${VERSION}"
   then
      local commits

      commits="`project::git::commits_from_tag "${VERSION}"`"
      if [ ! -z "${commits}" ]
      then
         log_warning "${VERSION} already exists as a git tag, but has commits"
      else
         if ! project::git::is_clean
         then
            log_warning "${VERSION} already exists as a git tag, but has uncommitted files"
         else
            last="`rexekutor git tag -l --sort=-creatordate | grep -E -x '[0-9]*\.[0-9]*\.[0-9]*' | head -1`"

            info_version "${VERSION}" "${last}"
         fi
      fi
   else
      last="`rexekutor git tag -l --sort=-creatordate | grep -E -x '[0-9]*\.[0-9]*\.[0-9]*' | head -1`"

      info_version "${VERSION}" "${last}"
   fi

   if [ "${OPTION_RELEASENOTES}" != 'NO' ]
   then
      info_releasenotes "${VERSION}"
   fi
}


edit_version()
{
   log_entry "edit_version" "$@"

   [ "${OPTION_ADD_MAJOR}" -ne 0 ] &&
      [ "${OPTION_ADD_MINOR}" -ne 0 -o "${OPTION_ADD_PATCH}" -ne 0 -o "${OPTION_ADD_CUSTOM}" -ne 0 ] &&
         fail "only specify major to increment"

   [ "${OPTION_ADD_MINOR}" -ne 0 ] &&
      [ "${OPTION_ADD_PATCH}" -ne 0 -o "${OPTION_ADD_CUSTOM}" -ne 0 ] &&
         fail "only specify minor to increment"

   [ "${OPTION_ADD_PATCH}" -ne 0 ] &&
      [ "${OPTION_ADD_CUSTOM}" -ne 0 ] &&
         fail "only specify patch to increment"

   OLDVERSION="${VERSION}"

   if [ "${OPTION_ADD_MAJOR}" -ne 0 -o \
        "${OPTION_ADD_MINOR}" -ne 0 -o \
        "${OPTION_ADD_PATCH}" -ne 0 -o \
        "${OPTION_ADD_CUSTOM}" -ne 0 ]
   then
      if [ -z "${VERSIONFILE}" ]
      then
         fail "Don't know how to increment version"
      fi

      VERSION="`project::version::add "${VERSION}" \
                                      "${OPTION_ADD_MAJOR}" \
                                      "${OPTION_ADD_MINOR}" \
                                      "${OPTION_ADD_PATCH}" \
                                      "${OPTION_ADD_CUSTOM}" \
                                      "0" \
                                      "${OPTION_FIRST_PATCH}" \
                                      "${OPTION_FIRST_CUSTOM}"`" || exit 1
   fi
}


emit_patched_cmakelists_txt() 
{
   log_entry "emit_patched_cmakelists_txt" "$@"

   local version="$1"

   local in_project=0
   local found=0

   while IFS=$'\n' read -r line
   do
      if [ $found -eq 0 ]
      then
         case "$line" in
            *project\(*)
               in_project=1
            ;;

            ""|'#'*)
               in_project=0
            ;;
         esac

         if [ $in_project -eq 1 ]
         then
            case "$line" in
               *VERSION*)
                  line=$(sed -E "s/(VERSION[[:space:]]*\"?)[0-9]+\.[0-9]+\.[0-9]+(\"?)/\1$version\2/" <<< "${line}")
                  found=1
               ;;
            esac
         fi
      fi
      printf "%s\n" "$line"
   done

   [ $found -eq 1 ]
   return $?
}


write_version()
{
   log_entry "write_version" "$@"

   if [ "${VERSIONIMMUTABLE}" = 'YES' ]
   then
      fail "Version is immutable (VERSIONIMMUTABLE=${VERSIONIMMUTABLE})"
   fi

   if [ "${OPTION_WRITE}" = 'YES' ]
   then
      #
      # small hack for extensions to distribute versioning
      # improve with namekeys later
      #
      local other

      .foreachline other in ${VERSIONFILEMIRRORS}
      .do
         if [ ! -z "${other}" ]
         then
            project::version::set "${VERSION}" \
                                  "${other}" \
                                  "${VERSIONMIRRORNAME}" \
                                  "${VERSIONCUSTOM}" || exit 1
         fi
      .done

      if [ ! -z "${VERSIONFILE}" ]
      then
         # Skip project::version::set for CMakeLists.txt with empty VERSIONNAME
         # It will be handled by emit_patched_cmakelists_txt
         if [ "${VERSIONFILE}" != "CMakeLists.txt" -o ! -z "${VERSIONNAME}" ]
         then
            project::version::set "${VERSION}" \
                                  "${VERSIONFILE}" \
                                  "${VERSIONNAME}" \
                                  "${VERSIONCUSTOM}" || exit 1
         fi
      fi
   fi

   if [ "${OPTION_WRITE_CMAKELISTS_TXT}" = 'YES' -a -f CMakeLists.txt ]
   then
      if text="`emit_patched_cmakelists_txt "${VERSION}" < CMakeLists.txt`"
      then
         redirect_exekutor CMakeLists.txt  printf "%s\n" "${text}"
      else
         log_warning "Failed to find version info in CMakeLists.txt"
      fi
   fi

   if [ "${OPTION_WRITE_XCODE_VERSION}" = 'YES' ]
   then
      inplace_sed -e 's|^\([[:space:]]*CURRENT_PROJECT_VERSION[[:space:]]*=[[:space:]]*["]*\)'${XCODE_VERSION}'\(.*\)|\1'${VERSION}'\2|' \
                     "${ACTUAL_XCODEPROJ}/project.pbxproj"
   fi

   if [ "${OPTION_WRITE_EXTENSION_VERSIONS}" = 'YES' ]
   then
      exekutor mulle-project-version-extensions --project-version "${VERSION}" bump
   fi
}


verify_version()
{
   log_entry "verify_version" "$@"

   # lame ass bug check
   case "$*" in
      *--reset*)
         _internal_fail "verify called too often"
      ;;
   esac

   VERIFY_VERSION="`rexekutor "${MULLE_EXECUTABLE}" "$@" --reset`" || _internal_fail "Could not get VERIFY_VERSION"

   if [ "${VERSION}" != "${VERIFY_VERSION}" ]
   then
      fail "Version could not be set to ${VERSION} (is ${VERIFY_VERSION})"
   else
      log_info "Version successfully set to ${VERSION}"
   fi

   return 0
}


diff_version()
{
   log_entry "diff_version" "$@"

   local current="$1"
   local last="$2"

   if [ -z "${last}" ]
   then
      echo "init"
      return 0
   fi

   if [ "${current}" = "${last}" ]
   then
      echo "none"
      return 0
   fi

   # Use mulle-bashfunctions version parsing
   local current_major current_minor current_patch
   local last_major last_minor last_patch

   # Parse current version
   current_major="${current%%\.*}"
   local temp="${current#*\.}"
   if [ "${temp}" = "${current}" ]
   then
      current_minor=0
      current_patch=0
   else
      current_minor="${temp%%\.*}"
      temp="${temp#*\.}"
      if [ "${temp}" = "${current_minor}" ]
      then
         current_patch=0
      else
         current_patch="${temp%%\.*}"
      fi
   fi

   # Parse last version
   last_major="${last%%\.*}"
   temp="${last#*\.}"
   if [ "${temp}" = "${last}" ]
   then
      last_minor=0
      last_patch=0
   else
      last_minor="${temp%%\.*}"
      temp="${temp#*\.}"
      if [ "${temp}" = "${last_minor}" ]
      then
         last_patch=0
      else
         last_patch="${temp%%\.*}"
      fi
   fi

   # Compare versions
   if [ "${current_major}" != "${last_major}" ]
   then
      echo "major"
   elif [ "${current_minor}" != "${last_minor}" ]
   then
      echo "minor"
   elif [ "${current_patch}" != "${last_patch}" ]
   then
      echo "patch"
   else
      echo "none"
   fi
}


cmd_init()
{
   log_entry "cmd_init" "$@"

   local versionfile="$1"
   local versionname="$2"

   local infofile=".mulle/etc/project/version-info.sh"

   if [ -f "${infofile}" ]
   then
      fail "Version info file already exists: ${infofile}"
   fi

   mkdir -p ".mulle/etc/project" || fail "Failed to create .mulle/etc/project"

   cat > "${infofile}" <<EOF
# -- Version Info --
#
# Keep these commented out, if the automatic detection works well
# enough for you.
#

EOF

   if [ ! -z "${versionfile}" ]
   then
      echo "VERSIONFILE=\"${versionfile}\"" >> "${infofile}"
   else
      echo "# VERSIONFILE=\"src/version.h\"" >> "${infofile}"
   fi

   if [ ! -z "${versionname}" ]
   then
      echo "VERSIONNAME=\"${versionname}\"" >> "${infofile}"
   else
      echo "# VERSIONNAME=\"VERSION\"" >> "${infofile}"
   fi

   cat >> "${infofile}" <<EOF

#
# Other files that get the version written into. Write only. Linefeed separated.
#
# VERSIONMIRRORNAME=version
# VERSIONFILEMIRRORS="
#src/version.txt"
EOF

   log_info "Created ${infofile}"
}


cmd_add()
{
   log_entry "cmd_add" "$@"

   local mirrorfile="$1"
   local infofile=".mulle/etc/project/version-info.sh"

   [ -z "${mirrorfile}" ] && fail "No mirror file specified"
   [ ! -f "${infofile}" ] && fail "Version info file not found. Run 'init' first."

   if grep -q "^VERSIONFILEMIRRORS=" "${infofile}"
   then
      # Check if already exists
      if grep -A100 "^VERSIONFILEMIRRORS=" "${infofile}" | grep -q "^${mirrorfile}\""
      then
         log_warning "Mirror file already exists: ${mirrorfile}"
         return 0
      fi
      
      # Add before the closing quote
      local tmpfile
      local text
      
      r_make_tmp_file "version-info"
      tmpfile="${RVAL}"
      
      text="$(awk -v mirror="${mirrorfile}" '
         /^VERSIONFILEMIRRORS=/ { 
            print
            in_mirrors=1
            next
         }
         in_mirrors && /"$/ { 
            print mirror
            in_mirrors=0
         }
         { print }
      ' "${infofile}")"
      
      redirect_exekutor "${tmpfile}" printf "%s\n" "${text}"
      exekutor mv "${tmpfile}" "${infofile}"
   else
      # Create new VERSIONFILEMIRRORS entry
      redirect_append_exekutor "${infofile}" echo ""
      redirect_append_exekutor "${infofile}" echo "VERSIONFILEMIRRORS=\""
      redirect_append_exekutor "${infofile}" echo "${mirrorfile}\""
   fi

   log_info "Added mirror file: ${mirrorfile}"
}


cmd_remove()
{
   log_entry "cmd_remove" "$@"

   local mirrorfile="$1"
   local infofile=".mulle/etc/project/version-info.sh"

   [ -z "${mirrorfile}" ] && fail "No mirror file specified"
   [ ! -f "${infofile}" ] && fail "Version info file not found"

   if ! grep -q "^VERSIONFILEMIRRORS=" "${infofile}"
   then
      log_warning "No mirror files configured"
      return 0
   fi

   # Use awk to remove the mirror line
   local tmpfile
   local text
   
   r_make_tmp_file "version-info"
   tmpfile="${RVAL}"
   
   text="$(awk -v mirror="${mirrorfile}" '
      $0 == mirror { next }
      { print }
   ' "${infofile}")"
   
   redirect_exekutor "${tmpfile}" printf "%s\n" "${text}"
   exekutor mv "${tmpfile}" "${infofile}"
   
   # If VERSIONFILEMIRRORS is now empty (ends with just "), remove it
   if grep -A1 '^VERSIONFILEMIRRORS="$' "${infofile}" | tail -1 | grep -q '^"$'
   then
      inplace_sed '/^VERSIONFILEMIRRORS="$/,/^"$/d' "${infofile}"
   fi
   
   log_info "Removed mirror file: ${mirrorfile}"
}


cmd_list()
{
   log_entry "cmd_list" "$@"

   local infofile=".mulle/etc/project/version-info.sh"

   if [ ! -f "${infofile}" ]
   then
      log_info "No version-info.sh found (using auto-detection)"
      return 0
   fi

   log_info "Configuration from ${infofile}:"
   echo ""
   exekutor cat "${infofile}"
}


main()
{
   local OPTION_ADD_MAJOR="0"
   local OPTION_ADD_MINOR="0"
   local OPTION_ADD_PATCH="0"
   local OPTION_ADD_CUSTOM="0"
   local OPTION_FIRST_PATCH="0"
   local OPTION_FIRST_CUSTOM="0"
   local OPTION_READ_INFO='YES'
   local OPTION_READ_XCODE_VERSION='NO'
   local OPTION_READ_CMAKELISTS_TXT='YES'
   local OPTION_WRITE='DEFAULT'
   local OPTION_WRITE_CMAKELISTS_TXT='YES'
   local OPTION_WRITE_XCODE_VERSION='DEFAULT'
   local OPTION_WRITE_EXTENSION_VERSIONS='DEFAULT'
   local OPTION_XCODEPROJ=""
   local OPTION_TAG_WARNING='YES'
   local OPTION_CUSTOM_VERSIONING
   local OPTION_VERSIONNAME
   local OPTION_VERSIONFILE
   local OPTION_IS_OK
   local OPTION_IF_NEEDED
   local OPTION_RELEASENOTES
   local OPTION_DIFF
   local OPTION_STATUS
   local OPTION_VERSION_SET

   local COMMAND=""
   local directory

   if [ -f ".mulle/etc/project/.first_patch" ]
   then
      OPTION_FIRST_PATCH="`cat ".mulle/etc/project/.first_patch"`"
   fi

   # Parse technical flags and options FIRST
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage
         ;;

         --no-cmake)
            OPTION_READ_CMAKELISTS_TXT='NO'
            OPTION_WRITE_CMAKELISTS_TXT='NO'
         ;;

         --no-cmake-read)
            OPTION_READ_CMAKELISTS_TXT='NO'
         ;;

         --no-cmake-write)
            OPTION_WRITE_CMAKELISTS_TXT='NO'
         ;;

         --no-info)
            OPTION_READ_INFO='NO'
         ;;

         --releasenotes)
            OPTION_RELEASENOTES='YES'
         ;;

         --no-releasenotes)
            OPTION_RELEASENOTES='NO'
         ;;

         ++)
            OPTION_ADD_PATCH="1"
            OPTION_WRITE='YES'
         ;;

         --custom-versioning)
            OPTION_CUSTOM_VERSIONING='YES'
         ;;

         --no-tag-warning)
            OPTION_TAG_WARNING='NO'
         ;;

         --ignore-untracked)
            r_concat "${MULLE_PROJECT_COMMIT_FLAGS}" "$1"
            MULLE_PROJECT_COMMIT_FLAGS="${RVAL}"
         ;;

         --increment-major)
            OPTION_ADD_MAJOR="1"
         ;;

         --increment-minor)
            OPTION_ADD_MINOR="1"
         ;;

         --increment-patch)
            OPTION_ADD_PATCH="1"
         ;;

         --increment-custom)
            OPTION_ADD_CUSTOM="1"
         ;;

         --if-needed)
            OPTION_IF_NEEDED='YES'
         ;;

         --print-latest-tag)
            project::git::last_tag
            exit $?
         ;;

         --first-patch-zero)
            OPTION_FIRST_PATCH="0"
         ;;

         --first-patch-one)
            OPTION_FIRST_PATCH="1"
         ;;

         --add-patch)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            OPTION_ADD_PATCH="$1"
         ;;

         --first-custom-one)
            OPTION_FIRST_CUSTOM="1"
         ;;

         --add-custom)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            OPTION_ADD_CUSTOM="$1"
         ;;

         --write)
            OPTION_WRITE='YES'
         ;;

         --no-write)
            OPTION_WRITE='NO'
         ;;

         --xcodeproj)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift

            OPTION_XCODEPROJ="$1"
         ;;

         --read-xcode-version)
            OPTION_READ_XCODE_VERSION='YES'
         ;;

         --write-xcode-version)
            OPTION_WRITE_XCODE_VERSION='YES'
         ;;

         --no-write-xcode-version)
            OPTION_WRITE_XCODE_VERSION='NO'
         ;;

         --write-extension-versions)
            OPTION_WRITE_EXTENSION_VERSIONS='YES'
         ;;

         --no-write-extension-versions)
            OPTION_WRITE_EXTENSION_VERSIONS='NO'
         ;;

         --language)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift
            LANGUAGE="$1"
         ;;

         --file|--versionfile)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift
            OPTION_VERSIONFILE="$1"
         ;;

         --name|--versionname)
            [ $# -eq 1 ] && fail "missing argument to $1"
            shift
            OPTION_VERSIONNAME="$1"
         ;;

         --reset) # stupid option for verify must be last in command line
            OPTION_IF_NEEDED=""
            OPTION_ADD_PATCH="0"
            OPTION_ADD_MINOR="0"
            OPTION_ADD_MAJOR="0"
            OPTION_ADD_CUSTOM="0"
            OPTION_WRITE_XCODE_VERSION='NO'
            OPTION_WRITE='NO'
            OPTION_WRITE_EXTENSION_VERSIONS='NO'
            OPTION_TAG_WARNING='NO'
         ;;

         -*)
            usage "Unknown option $1"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   # Now parse command
   if [ $# -gt 0 ]
   then
      case "$1" in
         get|set|try|init|add|remove|list|status|diff)
            COMMAND="$1"
            shift
         ;;
      esac
   fi

   # For backward compatibility, default to get
   [ -z "${COMMAND}" ] && COMMAND="get"

   # Handle subcommands that don't need project setup
   case "${COMMAND}" in
      init)
         local init_file=""
         local init_name=""
         
         while [ $# -ne 0 ]
         do
            case "$1" in
               --file)
                  [ $# -eq 1 ] && fail "missing argument to $1"
                  shift
                  init_file="$1"
               ;;
               --name)
                  [ $# -eq 1 ] && fail "missing argument to $1"
                  shift
                  init_name="$1"
               ;;
               *)
                  usage "Unknown option $1 for init"
               ;;
            esac
            shift
         done
         
         cmd_init "${init_file}" "${init_name}"
         return $?
      ;;

      add)
         [ $# -eq 0 ] && usage "add requires a file argument"
         cmd_add "$1"
         return $?
      ;;

      remove)
         [ $# -eq 0 ] && usage "remove requires a file argument"
         cmd_remove "$1"
         return $?
      ;;

      list)
         cmd_list
         return $?
      ;;
   esac

   # Handle set/try commands - extract version argument
   case "${COMMAND}" in
      set|try)
         [ $# -eq 0 ] && usage "${COMMAND} requires a version argument"
         OPTION_VERSION_SET="$1"
         shift
         
         if [ "${COMMAND}" = "set" ]
         then
            OPTION_WRITE='YES'
         else
            OPTION_WRITE='NO'
         fi
      ;;
      
      status)
         OPTION_STATUS='YES'
      ;;
      
      diff)
         OPTION_DIFF='YES'
      ;;
   esac


   local PROJECT_NAME
   local DIRECTORY_NAME

   r_basename "${PWD}"
   DIRECTORY_NAME="${RVAL}"

   log_setting "DIRECTORY_NAME=${DIRECTORY_NAME}"

   if [ $# -ne 0 ]
   then
      PROJECT_NAME="$1"
      shift
   fi
   if [ -z "${PROJECT_NAME}" ]
   then
      # use mulle-sde to navigate properly
      PROJECT_NAME="`mulle-sde env get PROJECT_NAME 2> /dev/null`"
   fi
   PROJECT_NAME="${PROJECT_NAME:-${DIRECTORY_NAME}}"

   log_setting "PROJECT_NAME=${PROJECT_NAME}"

   local VERSIONNAME
   local VERSIONFILE
   local VERSIONCUSTOM
   local VERSIONXCODEPROJ
   local VERSION
   local OLDVERSION

   if [ "${OPTION_READ_INFO}" = 'YES' ]
   then
      if [ -f "./.mulle/etc/project/version-info.sh" ]
      then
         log_debug "Reading \".mulle/etc/project/version-info.sh\""

         . ./.mulle/etc/project/version-info.sh
      fi
      if [ -f "./.mulle/etc/project/release-info.sh" ]
      then
         log_debug "Reading \".mulle/etc/project/release-info.sh\""

         . ./.mulle/etc/project/release-info.sh
      fi
      if [ -f "./.mulle/etc/project/formula-info.sh" ]
      then
         log_debug "Reading \".mulle/etc/project/formula-info.sh\""

         . ./.mulle/etc/project/formula-info.sh
      fi
   fi

   VERSIONNAME="${OPTION_VERSIONNAME:-${VERSIONNAME}}"
   VERSIONFILE="${OPTION_VERSIONFILE:-${VERSIONFILE}}"
   VERSIONCUSTOM="${OPTION_CUSTOM_VERSIONING:-${VERSIONCUSTOM}}"
   VERSIONXCODEPROJ="${OPTION_XCODEPROJ:-${VERSIONXCODEPROJ}}"

   # Handle NONE sentinel for CMakeLists.txt (convert before get_version)
   if [ "${VERSIONNAME}" = "NONE" ]
   then
      VERSIONNAME=""
   fi

   if [ "${OPTION_WRITE}" = "${DEFAULT}" ]
   then
      OPTION_WRITE="NO"
   fi

   if [ "${OPTION_WRITE_XCODE_VERSION}" = 'DEFAULT' ]
   then
      if [ "${OPTION_WRITE}" = "YES" ]
      then
         if [ -z "${VERSIONXCODEPROJ}" ]
         then
            OPTION_WRITE_XCODE_VERSION="NO"
         else
            OPTION_WRITE_XCODE_VERSION="YES"
         fi
      else
         OPTION_WRITE_XCODE_VERSION="NO"
      fi
   fi

   # do this by default
   if [ "${OPTION_WRITE_EXTENSION_VERSIONS}" = 'DEFAULT' ]
   then
      if [ "${OPTION_WRITE}" = "YES" ]
      then
         OPTION_WRITE_EXTENSION_VERSIONS="YES"
      else
         OPTION_WRITE_EXTENSION_VERSIONS="NO"
      fi
   fi

   include "project::version"
   include "project::git"

   get_version

   if [ "${OPTION_STATUS}" = 'YES' ]
   then
      status_version
      return $?
   fi

   if [ "${OPTION_DIFF}" = 'YES' ]
   then
      last="`rexekutor git tag -l --sort=-creatordate | grep -E -x '[0-9]*\.[0-9]*\.[0-9]*' | head -1`"
      diff_version "${VERSION}" "${last}"
      return 0
   fi

   if [ "${OPTION_IF_NEEDED}" = 'YES' ] && status_version
   then
      log_verbose "Nothing to do"
      return 0
   fi

   if [ ! -z "${OPTION_VERSION_SET}" ]
   then
      OLDVERSION="${VERSION}"
      VERSION="${OPTION_VERSION_SET}"
   else
      OLDVERSION="${VERSION}"
      edit_version
   fi

   log_setting "VERSION=${VERSION}"
   log_setting "VERSIONNAME=${VERSIONNAME}"
   log_setting "VERSIONFILE=${VERSIONFILE}"
   log_setting "VERSIONCUSTOM=${VERSIONCUSTOM}"
   log_setting "VERSIONXCODEPROJ=${VERSIONXCODEPROJ}"

   if [ "${OPTION_TAG_WARNING}" = 'YES' ]
   then
      warn_version
   fi

   if [ "${OPTION_WRITE}" = 'YES' \
        -o "${OPTION_WRITE_XCODE_VERSION}" = 'YES' \
        -o "${OPTION_WRITE_EXTENSION_VERSIONS}" = 'YES' ]
   then
      write_version "$@" &&
      verify_version "$@"
      return $?
   else
      if [ "${VERSION}" != "${OLDVERSION}" ]
      then
         log_warning "Use --write to affect version change"
      fi
   fi

   printf "%s\n" "${VERSION}"
   return 0
}


main "$@"
