#! /bin/sh

CMD="${1:-help}"

case "${CMD}" in 
   [0-9]*|v*)
      CMD="patch"
   ;;

   *)
      shift
   ;;
esac 

NEW_VERSION="${1:-17.0.6.2}"
NEW_CODENAME="${2:-bookworm}"
NEW_ARCH="${3-amd64}"

FILES="Dockerfile
*/Dockerfile
dox/*.md
bin/*
cola/*.bud"

OLD_VERSION=
OLD_CODENAME=
OLD_ARCH=

eval "$(
grep -RhoE 'mulle-clang-[^-]+-[^-]+-[^.]+\.deb' ${FILES} 2>/dev/null |
sed -E '
  s/mulle-clang-//;
  s/\.deb//;
  s/^([^-]+)-([^-]+)-(.+)$/OLD_VERSION=\1\nOLD_CODENAME=\2\nOLD_ARCH=\3/
'
)"


case "${CMD}" in 
   '--help')
      exe="`basename -- $0`"

      cat <<EOF >&2
Usage:
   ${exe} <new-version> [new-codename] [new-arch]

   Change URLs and other definitions of the mulle-clang-project version
   in Dockerfiles, README.md and installer files.

   OLD_VERSION="${OLD_VERSION}"
   OLD_CODENAME="${OLD_CODENAME}"
   OLD_ARCH="${OLD_ARCH}"

Example:
   ${exe} 16.0.0.0 bullseye bookworm

EOF
   ;;

   'list'|'--list')
      echo "OLD_VERSION=$OLD_VERSION"
      echo "OLD_CODENAME=$OLD_CODENAME"
      echo "OLD_ARCH=$OLD_ARCH"
      exit 0
   ;;
esac

echo "VERSION=$OLD_VERSION -> ${NEW_VERSION}"
echo "OLD_CODENAME=$OLD_CODENAME -> ${NEW_CODENAME}"
echo "OLD_ARCH=$OLD_ARCH -> ${NEW_ARCH}"


for file in ${FILES}
do
   if [ -f "${file}" ]
   then
      echo "$file" >&2

      mulle-replace "github.com/mulle-cc/mulle-clang-project/releases/download/${OLD_VERSION}/" \
                    "github.com/mulle-cc/mulle-clang-project/releases/download/${NEW_VERSION}/" \
                    "${file}"

      mulle-replace "mulle-clang-${OLD_VERSION}-${OLD_CODENAME}-${OLD_ARCH}.deb" \
                    "mulle-clang-${NEW_VERSION}-${NEW_CODENAME}-${NEW_ARCH}.deb" \
                    "${file}"

      mulle-replace "\${MULLE_CLANG_VERSION:-${OLD_VERSION}}" \
                    "\${MULLE_CLANG_VERSION:-${NEW_VERSION}}" \
                    "${file}"
   fi
done
