#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
# This script creates git submodule calls for a repository
#

IFS=$'\n'
for line in `mulle-sde -s dependency list -r \
                                          --columnar \
                                          -- "$@" \
                                             --dedupe-mode url-filename \
                                             --output-no-column \
                                             --output-no-header \
                                             --output-eval \
                                             --format '%n;%b;%u\n' `
do
   nodetype="${line%%;*}"
   line="${line#*;}"
   branch="${line%;*}"
   url="${line##*;}"

   case "${nodetype}" in
      tar)
         case "${url}" in
            *github.com/*)
               s="${url#*github.com/}"
               user="${s%%/*}"
               s="${s#*/}"
               repo="${s%%/*}"

               url="https://github.com/${user}/${repo}"
            ;;
         esac
      ;;

      git)
         repo="${url##*/}"
      ;;

      *)
         continue
      ;;
   esac

   printf "git submodule add -f"
   if [ ! -z "${branch}" ]
   then
      r_escaped_doublequotes "${branch}"
      printf " -b \"%s\"" "${RVAL}"
   fi

   r_escaped_doublequotes "${repo}"
   printf " --name \"%s\"" "${RVAL}"

   r_escaped_doublequotes "${url}"
   printf " \"%s\"" "${url}"

   r_escaped_doublequotes "${repo}"
   printf " \"stash/%s\"\n" "${RVAL}"
done

echo mulle-sde environment --global set MULLE_FETCH_SEARCH_PATH \
"'"'${PWD}/stash:${MULLE_FETCH_SEARCH_PATH}'"'"
