#! /usr/bin/env bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"


show_function()
{
   declare -f "$1" | \
      sed -e '1,2d' -e '$d' | \
      sed -e 's/^    //' | \
      sed -e 's/exekutor //g' | \
      sed -e "s/&&/^  /g" | \
      tr '^' '\n'
}

usage()
{
   [ "$#" -ne 0 ] && log_error "$1"

   cat <<EOF >&2
Usage:
   ${MULLE_USAGE_NAME} <message>

   A lazy and sloppy way to push out a patch. It does:

   `show_function "sloppy_commit"`
   `show_function "sloppy_push"`
EOF
   exit 1
}

sloppy_commit()
{
   exekutor git add -u &&
   exekutor git commit -m "* $*"
}


sloppy_push()
{
   exekutor mulle-project-version --increment-patch --write &&
   [ ! -f "RELEASENOTES.md" ] || exekutor mulle-project-releasenotes RELEASENOTES.md &&
   exekutor git add -u &&
   exekutor git commit --amend --no-edit &&
   exekutor mulle-project-distribute
}


sloppy_distribute()
{
   if [ $# -ne 0 ]
   then
      sloppy_commit "$@" || exit 1
   fi

   sloppy_push
}


git_is_clean()
{
   log_entry "git_is_clean" "$@"

   local name

   name="${1:-${PWD}}"

   if [ ! -d .git ]
   then
      fail "\"${name}\" is not a git repository"
   fi

   local clean

   clean=`git status -s --untracked-files=no`
   [ -z "${clean}" ]
}


main()
{
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help|help)
            usage
         ;;

         -*)
            usage "unknown option \"$1\""
         ;;

         *)
            break
         ;;
      esac
   done

   options_setup_trace "${MULLE_TRACE}"

   untracked="`exekutor git ls-files --others --exclude-standard`"
   if [ ! -z "${untracked}" ]
   then
      fail "There are still untracked files here, can't be that sloppy"
   fi

   if ! git_is_clean && [ $# -eq 0 ]
   then
      log_error "Need a commit message for the outstandig commits"
      git status -s
      exit 1
   fi

   sloppy_distribute "$@"
}


_init()
{
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
         echo "mulle-bashfunctions-env not installed" >&2 && \
         exit 1
   fi

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
}

_init "$@"
main "$@"


